import { useState } from 'react'
import { Link } from 'react-router-dom'
import { QRCodeSVG } from 'qrcode.react'
export default function ConductorPortal() {
  const [ticket, setTicket] = useState(null); const [count, setCount] = useState(59)
  const generate = () => { const number = count + 1; setCount(number); setTicket({ id: `BMTC-${Date.now().toString().slice(-6)}`, number, time: new Date().toLocaleTimeString('en-IN') }) }
  const qrUrl = `${window.location.origin}/passenger?ticket=${ticket?.id || 'demo'}&bus=KA-01-F-1234`
  return <main className="min-h-screen bg-neutral-950 p-5 text-white"><div className="mx-auto max-w-md"><Link to="/" className="text-xs font-bold text-orange-500">← NAVBHARAT</Link><header className="mt-7 border-b border-white/15 pb-5"><p className="text-xs font-bold tracking-widest text-orange-500">CONDUCTOR TERMINAL</p><h1 className="mt-2 text-2xl font-semibold">KA 01 F 1234</h1><p className="mt-1 text-sm text-neutral-400">Route 500D · Silk Board to Hebbal</p></header><section className="mt-5 rounded-xl border border-white/15 bg-neutral-900 p-5"><div className="flex items-center justify-between"><p className="text-sm font-medium">Passenger capacity</p><span className="text-xs text-orange-300">Limit 59</span></div><p className="mt-4 text-4xl font-semibold">{count}<span className="text-lg text-neutral-500"> / 59</span></p><div className="mt-4 h-2 rounded-full bg-white/10"><div className="h-full rounded-full bg-orange-500" /></div></section><section className="mt-4 rounded-xl border border-white/15 bg-neutral-900 p-5"><div className="flex justify-between text-sm"><span>Majestic → Indiranagar</span><b className="text-orange-300">₹60</b></div><button onClick={generate} className="mt-5 w-full rounded-md bg-orange-500 p-3 text-sm font-bold text-black">Generate ticket · ₹60</button></section>{ticket && <><section className="mt-4 rounded-xl border border-orange-500/50 bg-white p-5 text-black"><div className="flex items-start justify-between"><div><p className="text-xs font-bold tracking-widest text-orange-600">NAVBHARAT TICKET</p><p className="mt-2 text-xl font-semibold">₹60.00</p><p className="mt-2 text-xs">{ticket.id} · {ticket.time}<br />Bus KA 01 F 1234 · Route 500D</p></div><QRCodeSVG value={qrUrl} size={108} /></div><p className="mt-4 border-t border-black/10 pt-3 text-xs text-neutral-600">Scan this QR to open the passenger journey page with live map, stops, and safety reporting.</p></section><div role="alert" className="mt-4 rounded-xl border border-orange-500/50 bg-orange-500/10 p-4 text-sm text-orange-100"><b>Capacity alert: bus overloaded by {ticket.number - 59} person.</b><p className="mt-1 text-xs text-orange-200/80">5 people are waiting at the next stop. Consider dispatching support.</p></div></>}</div></main>
}
