import { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { evidence, saveEvidence } from '../lib/evidenceStore'
const title = { 'dept-1': 'Road Maintenance — Department 1', 'dept-2': 'Road Maintenance — Department 2', 'dept-3': 'Drainage — Department 3' }
export default function DepartmentPortal() {
  const { departmentId } = useParams(); const [items, setItems] = useState(evidence()); const [active, setActive] = useState(null)
  useEffect(() => { const refresh = () => setItems(evidence()); window.addEventListener('evidence-update', refresh); return () => window.removeEventListener('evidence-update', refresh) }, [])
  const queue = items.filter((x) => x.department === departmentId); const update = (status) => { const all = items.map((x) => x.id === active.id ? { ...x, status } : x); saveEvidence(all); setItems(all); setActive({ ...active, status }) }
  return <main className="min-h-screen bg-neutral-950 text-white"><header className="flex items-center justify-between border-b border-white/15 px-5 py-4"><div><Link to="/" className="text-xs font-bold text-orange-500">NAVBHARAT OFFICIAL</Link><h1 className="mt-1 text-sm font-semibold">{title[departmentId] || 'Department queue'} · East Bengaluru</h1></div><span className="rounded-full bg-orange-500/10 px-3 py-1 text-xs text-orange-300">{queue.filter((x) => x.status === 'New').length} pending works</span></header><div className="mx-auto grid max-w-6xl gap-5 p-5 lg:grid-cols-[1.3fr_.7fr]"><section><div className="mb-3 flex justify-between"><p className="text-xs font-bold uppercase tracking-widest text-neutral-500">Detected potholes & video evidence</p><p className="text-xs text-neutral-400">{queue.length} reports</p></div><div className="space-y-3">{queue.map((item) => <button key={item.id} onClick={() => setActive(item)} className="w-full rounded-xl border border-white/15 bg-neutral-900 p-4 text-left hover:border-orange-500"><div className="flex justify-between gap-3"><div><p className="font-medium">{item.file}</p><p className="mt-1 text-xs text-neutral-400">{item.location} · {item.date}</p></div><span className="h-fit rounded-full bg-orange-500/10 px-2 py-1 text-[11px] text-orange-300">{item.severity} severity</span></div><div className="mt-4 flex gap-4 text-xs text-neutral-400"><span>{item.id}</span><span>{item.coordinates}</span><span>{item.status}</span></div></button>)}</div></section><aside className="rounded-xl border border-white/15 bg-neutral-900 p-5">{active ? <><p className="text-xs font-bold uppercase tracking-widest text-orange-500">Evidence & field metadata</p><div className="mt-5 grid h-44 place-items-center rounded-lg border border-white/10 bg-black text-center text-sm text-neutral-400"><div><span className="inline-block h-3 w-3 animate-pulse rounded-full bg-orange-500" /><p className="mt-3">Evidence video loading</p><p className="mt-1 text-xs text-neutral-600">Awaiting secure department stream</p></div></div><dl className="mt-5 grid grid-cols-2 gap-4 text-sm"><div><dt className="text-xs text-neutral-500">Coordinates</dt><dd>{active.coordinates}</dd></div><div><dt className="text-xs text-neutral-500">Locality</dt><dd>{active.location}</dd></div><div><dt className="text-xs text-neutral-500">Reported</dt><dd>{active.date}</dd></div><div><dt className="text-xs text-neutral-500">Severity / status</dt><dd>{active.severity} · {active.status}</dd></div></dl><div className="mt-6 flex gap-2"><button onClick={() => update('Assigned')} className="flex-1 rounded-md border border-white/15 p-2 text-xs">Assign crew</button><button onClick={() => update('Fixed')} className="flex-1 rounded-md bg-orange-500 p-2 text-xs font-bold text-black">Mark fixed</button></div></> : <p className="text-sm text-neutral-500">Select a report to inspect its evidence video and field metadata.</p>}</aside></div></main>
}
