import { Link } from 'react-router-dom'

const capabilities = [
  ['Road intelligence', 'Field video evidence helps departments identify potholes, verify their location, and assign work faster.'],
  ['Connected operations', 'Each report carries a clear status—from newly detected to crew assigned and fixed—so teams can act with confidence.'],
  ['Passenger safety', 'Live bus journeys, stop information, and contextual safety reporting help make every trip more informed.'],
]

export default function Landing() {
  return <main className="min-h-screen bg-neutral-950 px-5 py-8 text-white sm:px-10"><header className="mx-auto flex max-w-6xl items-center border-b border-white/15 pb-5"><Link to="/" className="font-bold tracking-tight">NAV<span className="text-orange-500">BHARAT</span></Link><span className="ml-auto text-xs text-neutral-500">Urban Mobility Intelligence</span></header><section className="mx-auto max-w-6xl py-20 sm:py-28"><p className="text-xs font-bold uppercase tracking-[.24em] text-orange-500">Built for Bengaluru</p><h1 className="mt-4 max-w-4xl text-4xl font-semibold tracking-tight sm:text-6xl">Safer streets. Better journeys.</h1><p className="mt-6 max-w-2xl text-base leading-7 text-neutral-300">NavBharat brings road-condition evidence, department action tracking, and public-transit awareness into one practical urban mobility system.</p><p className="mt-3 max-w-2xl text-sm leading-6 text-neutral-500">It turns an on-ground video report into a traceable task for the right city department, while giving passengers useful, ticket-linked journey information.</p><div className="mt-14 grid gap-3 md:grid-cols-3">{capabilities.map(([title, description], index) => <article key={title} className="rounded-xl border border-white/15 bg-white/[.03] p-6"><p className="text-xs font-bold text-orange-500">0{index + 1}</p><h2 className="mt-8 text-lg font-semibold">{title}</h2><p className="mt-3 text-sm leading-6 text-neutral-400">{description}</p></article>)}</div><section className="mt-14 max-w-4xl border-l-2 border-orange-500 pl-5"><p className="text-sm font-medium">From detection to resolution</p><p className="mt-2 text-sm leading-6 text-neutral-400">Evidence is submitted, routed by department, reviewed with location metadata, assigned for action, and monitored through city-level operations. Passenger reporting adds context to safety incidents without interrupting the journey experience.</p></section></section><footer className="mx-auto max-w-6xl border-t border-white/10 py-5 text-xs text-neutral-600">NavBharat Transit Intelligence · Smart India Hackathon demonstration</footer></main>
}
